-- =============================================================================
-- PetGuardian — DDL das Tabelas CORE
-- Banco de Dados: PostgreSQL 16
-- Disciplina: DevOps Tools & Cloud Computing — Sprint 3
-- =============================================================================
-- Este script cria apenas as tabelas que representam o núcleo (CORE) da solução
-- PetGuardian: gestão colaborativa de cuidados de pets.
-- Tabelas de suporte (endereco, cidade, estado, bairro, trilha, etc.) omitidas.
-- =============================================================================

-- -----------------------------------------------------------------------------
-- Tabela: raca
-- Domínio de raças de animais. Necessária para criar um Pet.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS raca
(
    id_raca   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome_raca VARCHAR(30)                             NOT NULL,
    CONSTRAINT pk_raca PRIMARY KEY (id_raca),
    CONSTRAINT uc_raca_nome_raca UNIQUE (nome_raca)
);

COMMENT ON TABLE raca IS 'Catálogo de raças de animais domésticos aceitos pela plataforma.';
COMMENT ON COLUMN raca.id_raca IS 'Identificador único da raça (auto-incremento).';
COMMENT ON COLUMN raca.nome_raca IS 'Nome da raça do animal (ex: Labrador, Persa, SRD). Deve ser único.';

-- -----------------------------------------------------------------------------
-- Tabela: pet
-- Entidade central da solução. Representa o animal sob cuidado colaborativo.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS pet
(
    id_pet       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome         VARCHAR(30)                             NOT NULL,
    data_nasc    DATE                                    NOT NULL,
    raca_id_raca BIGINT                                  NOT NULL,
    porte        VARCHAR(10)                             NOT NULL,
    sexo         CHAR(1)                                 NOT NULL,
    castrado     BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_pet PRIMARY KEY (id_pet),
    CONSTRAINT fk_pet_raca FOREIGN KEY (raca_id_raca) REFERENCES raca (id_raca)
);

COMMENT ON TABLE pet IS 'Entidade central da solução: representa o animal sob cuidado colaborativo da família/grupo de tutores.';
COMMENT ON COLUMN pet.id_pet IS 'Identificador único do pet (auto-incremento).';
COMMENT ON COLUMN pet.nome IS 'Nome do animal de estimação.';
COMMENT ON COLUMN pet.data_nasc IS 'Data de nascimento do pet. Usada para cálculo de idade e alertas de saúde.';
COMMENT ON COLUMN pet.raca_id_raca IS 'Chave estrangeira para a raça do pet. Referencia raca(id_raca).';
COMMENT ON COLUMN pet.porte IS 'Porte físico do animal. Valores aceitos: PEQUENO, MEDIO, GRANDE.';
COMMENT ON COLUMN pet.sexo IS 'Sexo do animal: M (macho) ou F (fêmea).';
COMMENT ON COLUMN pet.castrado IS 'Indica se o animal foi castrado. Impacta alertas de saúde preventiva.';

-- -----------------------------------------------------------------------------
-- Tabela: status
-- Domínio de estados possíveis de uma tarefa de cuidado.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS status
(
    id_status   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome_status VARCHAR(15)                             NOT NULL,
    CONSTRAINT pk_status PRIMARY KEY (id_status),
    CONSTRAINT uc_status_nome_status UNIQUE (nome_status)
);

COMMENT ON TABLE status IS 'Catálogo de estados possíveis para tarefas de cuidado do pet.';
COMMENT ON COLUMN status.id_status IS 'Identificador único do status (auto-incremento).';
COMMENT ON COLUMN status.nome_status IS 'Descrição do estado: PENDENTE, CONCLUIDO ou EXPIRADO.';

-- Carga inicial dos status padrão da plataforma
INSERT INTO status (nome_status) VALUES ('PENDENTE')  ON CONFLICT DO NOTHING;
INSERT INTO status (nome_status) VALUES ('CONCLUIDO') ON CONFLICT DO NOTHING;
INSERT INTO status (nome_status) VALUES ('EXPIRADO')  ON CONFLICT DO NOTHING;

-- -----------------------------------------------------------------------------
-- Tabela: telefone
-- Necessária como dependência da tabela usuario.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS telefone
(
    id_telefone BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    num_ddd     VARCHAR(2)                              NOT NULL,
    num_tel     VARCHAR(9)                              NOT NULL,
    CONSTRAINT pk_telefone PRIMARY KEY (id_telefone)
);

COMMENT ON TABLE telefone IS 'Dados de contato telefônico dos usuários da plataforma.';
COMMENT ON COLUMN telefone.id_telefone IS 'Identificador único do telefone (auto-incremento).';
COMMENT ON COLUMN telefone.num_ddd IS 'Código de área (DDD) com 2 dígitos (ex: 11, 21, 47).';
COMMENT ON COLUMN telefone.num_tel IS 'Número do telefone com 8 ou 9 dígitos, sem formatação.';

-- -----------------------------------------------------------------------------
-- Tabela: usuario
-- Representa o tutor ou co-cuidador que se cadastra na plataforma.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS usuario
(
    id_usuario           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome                 VARCHAR(100)                            NOT NULL,
    email                VARCHAR(50)                             NOT NULL,
    senha                VARCHAR(60)                             NOT NULL,
    role                 VARCHAR(10)                             NOT NULL,
    telefone_id_telefone BIGINT                                  NOT NULL,
    CONSTRAINT pk_usuario PRIMARY KEY (id_usuario),
    CONSTRAINT uc_usuario_email UNIQUE (email),
    CONSTRAINT fk_usuario_telefone FOREIGN KEY (telefone_id_telefone) REFERENCES telefone (id_telefone)
);

COMMENT ON TABLE usuario IS 'Representa o tutor principal ou co-cuidador que usa a plataforma para gerenciar cuidados colaborativos do pet.';
COMMENT ON COLUMN usuario.id_usuario IS 'Identificador único do usuário (auto-incremento).';
COMMENT ON COLUMN usuario.nome IS 'Nome completo do usuário.';
COMMENT ON COLUMN usuario.email IS 'E-mail de acesso único à plataforma. Usado como identificador de login.';
COMMENT ON COLUMN usuario.senha IS 'Senha criptografada via BCrypt (60 caracteres).';
COMMENT ON COLUMN usuario.role IS 'Perfil de acesso: USER ou ADMIN.';
COMMENT ON COLUMN usuario.telefone_id_telefone IS 'Chave estrangeira para o telefone do usuário. Referencia telefone(id_telefone).';

-- -----------------------------------------------------------------------------
-- Tabela: usuario_pet  (TABELA ASSOCIATIVA — Círculo de Cuidado Colaborativo)
-- Relação N:N entre Usuario e Pet. Implementa o conceito de Rede de Cuidado.
-- Um pet pode ter múltiplos cuidadores; um usuário pode cuidar de múltiplos pets.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS usuario_pet
(
    usuario_id_usuario BIGINT  NOT NULL,
    pet_id_pet         BIGINT  NOT NULL,
    respon_princ       BOOLEAN NOT NULL,
    CONSTRAINT pk_usuario_pet PRIMARY KEY (usuario_id_usuario, pet_id_pet),
    CONSTRAINT fk_usuario_pet_usuario FOREIGN KEY (usuario_id_usuario) REFERENCES usuario (id_usuario),
    CONSTRAINT fk_usuario_pet_pet FOREIGN KEY (pet_id_pet) REFERENCES pet (id_pet)
);

COMMENT ON TABLE usuario_pet IS 'Tabela associativa N:N que implementa o Círculo de Cuidado Colaborativo: vincula tutores/co-cuidadores a um ou mais pets. Pilar central do modelo PetGuardian.';
COMMENT ON COLUMN usuario_pet.usuario_id_usuario IS 'FK para o usuário cuidador. Compõe a chave primária composta.';
COMMENT ON COLUMN usuario_pet.pet_id_pet IS 'FK para o pet sob cuidado. Compõe a chave primária composta.';
COMMENT ON COLUMN usuario_pet.respon_princ IS 'Indica se o usuário é o Responsável Principal do pet (true) ou co-cuidador (false). Apenas o responsável principal pode convidar outros cuidadores.';

-- -----------------------------------------------------------------------------
-- Tabela: tarefa
-- Tarefa de cuidado prescrita para um pet. Entidade de CRUD principal da Sprint 3.
-- Relacionada diretamente com pet (N:1) e usuario (N:1).
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS tarefa
(
    id_tarefa          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    titulo             VARCHAR(30)                             NOT NULL,
    pontos_tarefa      INTEGER                                 NOT NULL,
    descricao          VARCHAR(200)                            NOT NULL,
    criacao            TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    prazo              TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    conclusao          TIMESTAMP(6) WITHOUT TIME ZONE,
    status_id_status   BIGINT                                  NOT NULL,
    usuario_id_usuario BIGINT                                  NOT NULL,
    pet_id_pet         BIGINT                                  NOT NULL,
    CONSTRAINT pk_tarefa PRIMARY KEY (id_tarefa),
    CONSTRAINT fk_tarefa_status FOREIGN KEY (status_id_status) REFERENCES status (id_status),
    CONSTRAINT fk_tarefa_usuario FOREIGN KEY (usuario_id_usuario) REFERENCES usuario (id_usuario),
    CONSTRAINT fk_tarefa_pet FOREIGN KEY (pet_id_pet) REFERENCES pet (id_pet)
);

COMMENT ON TABLE tarefa IS 'Tarefa de cuidado prescrita para um pet por um cuidador. É a entidade principal de CRUD: inclui criação, leitura, atualização, conclusão e exclusão de responsabilidades de saúde/bem-estar do animal.';
COMMENT ON COLUMN tarefa.id_tarefa IS 'Identificador único da tarefa (auto-incremento).';
COMMENT ON COLUMN tarefa.titulo IS 'Título resumido da tarefa de cuidado (ex: Vacina Antirrábica, Banho, Consulta).';
COMMENT ON COLUMN tarefa.pontos_tarefa IS 'Pontuação que o cuidador ganha ao concluir a tarefa. Base do sistema de gamificação.';
COMMENT ON COLUMN tarefa.descricao IS 'Descrição detalhada do cuidado prescrito.';
COMMENT ON COLUMN tarefa.criacao IS 'Timestamp de criação da tarefa na plataforma.';
COMMENT ON COLUMN tarefa.prazo IS 'Prazo limite para conclusão da tarefa. Após esse horário, o sistema marca como EXPIRADO.';
COMMENT ON COLUMN tarefa.conclusao IS 'Timestamp da conclusão efetiva. NULL enquanto pendente.';
COMMENT ON COLUMN tarefa.status_id_status IS 'FK para o estado atual da tarefa: PENDENTE, CONCLUIDO ou EXPIRADO.';
COMMENT ON COLUMN tarefa.usuario_id_usuario IS 'FK para o cuidador responsável pela execução desta tarefa.';
COMMENT ON COLUMN tarefa.pet_id_pet IS 'FK para o pet beneficiado pelo cuidado desta tarefa.';

-- -----------------------------------------------------------------------------
-- Tabela: historico
-- Registro cronológico de eventos clínicos e de cuidado do pet.
-- Relacionada com pet (N:1).
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS historico
(
    id_hist    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo_hist  VARCHAR(30)                             NOT NULL,
    data_hist  TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    pet_id_pet BIGINT                                  NOT NULL,
    CONSTRAINT pk_historico PRIMARY KEY (id_hist),
    CONSTRAINT fk_historico_pet FOREIGN KEY (pet_id_pet) REFERENCES pet (id_pet)
);

COMMENT ON TABLE historico IS 'Histórico cronológico de eventos clínicos e de cuidado associados a um pet. Consolida vacinas, consultas, pesagens e outros atendimentos veterinários.';
COMMENT ON COLUMN historico.id_hist IS 'Identificador único do registro histórico (auto-incremento).';
COMMENT ON COLUMN historico.tipo_hist IS 'Tipo do evento registrado (ex: VACINA, CONSULTA, PESAGEM, BANHO).';
COMMENT ON COLUMN historico.data_hist IS 'Data e hora do evento clínico ou de cuidado.';
COMMENT ON COLUMN historico.pet_id_pet IS 'FK para o pet ao qual este registro de histórico pertence.';
