// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using PetGuardian.Infrastructure.Persistence;

#nullable disable

namespace PetGuardian.Infrastructure.Migrations
{
    [DbContext(typeof(PetGuardianContext))]
    [Migration("20260830005248_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PetGuardian.Domain.Entities.Aula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_aula");

                    b.Property<int>("Concluida")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("concluida");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("NVARCHAR2(1000)")
                        .HasColumnName("conteudo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("descricao");

                    b.Property<string>("Dificuldade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("dificuldade");

                    b.Property<Guid>("ModuloId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("modulo_id_modulo");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("nome");

                    b.Property<short>("PontosAula")
                        .HasColumnType("NUMBER(5)")
                        .HasColumnName("pontos_aula");

                    b.HasKey("Id");

                    b.HasIndex("ModuloId");

                    b.ToTable("aula", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Bairro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_bairro");

                    b.Property<Guid>("CidadeId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("cidade_id_cidade");

                    b.Property<string>("NomeBairro")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("nome_bairro");

                    b.HasKey("Id");

                    b.HasIndex("CidadeId");

                    b.ToTable("bairro", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Cidade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_cidade");

                    b.Property<Guid>("EstadoId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("estado_id_estado");

                    b.Property<string>("NomeCidade")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("nome_cidade");

                    b.HasKey("Id");

                    b.HasIndex("EstadoId");

                    b.ToTable("cidade", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Endereco", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_endereco");

                    b.Property<Guid>("BairroId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("bairro_id_bairro");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("NVARCHAR2(8)")
                        .HasColumnName("cep");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("NVARCHAR2(5)")
                        .HasColumnName("numero");

                    b.Property<string>("Rua")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("NVARCHAR2(150)")
                        .HasColumnName("rua");

                    b.HasKey("Id");

                    b.HasIndex("BairroId");

                    b.ToTable("endereco", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Estado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_estado");

                    b.Property<string>("NomeEstado")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("nome_estado");

                    b.HasKey("Id");

                    b.ToTable("estado", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Historico", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_hist");

                    b.Property<DateTime>("DataHist")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("data_hist");

                    b.Property<Guid>("PetId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("pet_id_pet");

                    b.Property<string>("TipoHist")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("tipo_hist");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("historico", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Modulo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_modulo");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("nome");

                    b.Property<string>("TempoConclusao")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("tempo_conclusao");

                    b.Property<Guid>("TrilhaId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("trilha_id_trilha");

                    b.HasKey("Id");

                    b.HasIndex("TrilhaId");

                    b.ToTable("modulo", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Pet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_pet");

                    b.Property<int>("Castrado")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("castrado");

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("DATE")
                        .HasColumnName("data_nasc");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("nome");

                    b.Property<string>("Porte")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("porte");

                    b.Property<Guid>("RacaId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("raca_id_raca");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("sexo");

                    b.HasKey("Id");

                    b.HasIndex("RacaId");

                    b.ToTable("pet", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Raca", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_raca");

                    b.Property<string>("NomeRaca")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("nome_raca");

                    b.HasKey("Id");

                    b.ToTable("raca", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_status");

                    b.Property<string>("NomeStatus")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("NVARCHAR2(15)")
                        .HasColumnName("nome_status");

                    b.HasKey("Id");

                    b.ToTable("status", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Tarefa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_tarefa");

                    b.Property<DateTime?>("Conclusao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("conclusao");

                    b.Property<DateTime>("Criacao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("criacao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("descricao");

                    b.Property<Guid>("PetId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("pet_id_pet");

                    b.Property<byte>("PontosTarefa")
                        .HasColumnType("NUMBER(3)")
                        .HasColumnName("pontos_tarefa");

                    b.Property<DateTime>("Prazo")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("prazo");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("status_id_status");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("titulo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("usuario_id_usuario");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.HasIndex("StatusId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("tarefa", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Telefone", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_telefone");

                    b.Property<string>("NumDdd")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("num_ddd");

                    b.Property<string>("NumTel")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("NVARCHAR2(9)")
                        .HasColumnName("num_tel");

                    b.HasKey("Id");

                    b.ToTable("telefone", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Trilha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_trilha");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("NVARCHAR2(200)")
                        .HasColumnName("descricao");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("nome");

                    b.Property<Guid>("PetId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("pet_id_pet");

                    b.HasKey("Id");

                    b.HasIndex("PetId");

                    b.ToTable("trilha", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("RAW(16)")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("nome");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("role");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)")
                        .HasColumnName("senha");

                    b.Property<Guid>("TelefoneId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("telefone_id_telefone");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TelefoneId")
                        .IsUnique();

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.UsuarioEndereco", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("usuario_id_usuario");

                    b.Property<Guid>("EnderecoId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("endereco_id_endereco");

                    b.HasKey("UsuarioId", "EnderecoId");

                    b.HasIndex("EnderecoId");

                    b.ToTable("usuario_endereco", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.UsuarioPet", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("usuario_id_usuario");

                    b.Property<Guid>("PetId")
                        .HasColumnType("RAW(16)")
                        .HasColumnName("pet_id_pet");

                    b.Property<int>("ResponPrinc")
                        .HasColumnType("NUMBER(1)")
                        .HasColumnName("respon_princ");

                    b.HasKey("UsuarioId", "PetId");

                    b.HasIndex("PetId");

                    b.ToTable("usuario_pet", (string)null);
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Aula", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Modulo", "Modulo")
                        .WithMany("Aulas")
                        .HasForeignKey("ModuloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Modulo");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Bairro", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Cidade", "Cidade")
                        .WithMany("Bairros")
                        .HasForeignKey("CidadeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cidade");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Cidade", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Estado", "Estado")
                        .WithMany("Cidades")
                        .HasForeignKey("EstadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Estado");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Endereco", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Bairro", "Bairro")
                        .WithMany("Enderecos")
                        .HasForeignKey("BairroId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bairro");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Historico", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Pet", "Pet")
                        .WithMany("Historicos")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Modulo", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Trilha", "Trilha")
                        .WithMany("Modulos")
                        .HasForeignKey("TrilhaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trilha");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Pet", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Raca", "Raca")
                        .WithMany("Pets")
                        .HasForeignKey("RacaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Raca");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Tarefa", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Pet", "Pet")
                        .WithMany("Tarefas")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetGuardian.Domain.Entities.Status", "Status")
                        .WithMany("Tarefas")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PetGuardian.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Tarefas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("Status");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Trilha", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Pet", "Pet")
                        .WithMany("Trilhas")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Telefone", "Telefone")
                        .WithOne()
                        .HasForeignKey("PetGuardian.Domain.Entities.Usuario", "TelefoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Telefone");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.UsuarioEndereco", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Endereco", "Endereco")
                        .WithMany()
                        .HasForeignKey("EnderecoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetGuardian.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Enderecos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Endereco");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.UsuarioPet", b =>
                {
                    b.HasOne("PetGuardian.Domain.Entities.Pet", "Pet")
                        .WithMany("UsuariosPet")
                        .HasForeignKey("PetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PetGuardian.Domain.Entities.Usuario", "Usuario")
                        .WithMany("PetsVinculados")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pet");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Bairro", b =>
                {
                    b.Navigation("Enderecos");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Cidade", b =>
                {
                    b.Navigation("Bairros");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Estado", b =>
                {
                    b.Navigation("Cidades");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Modulo", b =>
                {
                    b.Navigation("Aulas");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Pet", b =>
                {
                    b.Navigation("Historicos");

                    b.Navigation("Tarefas");

                    b.Navigation("Trilhas");

                    b.Navigation("UsuariosPet");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Raca", b =>
                {
                    b.Navigation("Pets");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Status", b =>
                {
                    b.Navigation("Tarefas");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Trilha", b =>
                {
                    b.Navigation("Modulos");
                });

            modelBuilder.Entity("PetGuardian.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Enderecos");

                    b.Navigation("PetsVinculados");

                    b.Navigation("Tarefas");
                });
#pragma warning restore 612, 618
        }
    }
}
